### ISSUE TITLE
Series with more than 10 images appear in wrong order

### ISSUE THREAD

**Issue by jonathanwestin** [CDH-DevTeam/arosenius-archive-gui#24]
When a series of images (Kattresan is the only one I have found) has more than 10 images, the following thing happens:

1) the series-gallery displays them in the wrong order since it is based on the names of the individual painting. i.e "Lillans kattresa (1 av 32)" is followed by Lillans kattresa (10 av 32) instead of Lillans kattresa (2 av 32).

2) the series gallery only displays ten images, so the rest of the images (21 in total) is not accessible

**Comment by arildm** [comment]
About (2): Isn't the "Visa alla" button suitable to show all images?

<img width="500" alt="Screenshot 2022-03-02 at 20 35 25" src="https://user-images.githubusercontent.com/1454404/156436677-9459700e-7784-4b71-bf3e-4dc9fb191594.png">

**Comment by jonathanwestin** [comment]
That brings us to the big gallery view, which is not sorted alphabetically. And it is important that the thumbnails of all images in the series are displayed in relation to the present full picture.

**Comment by arildm** [comment]
Fixed in the backend: https://github.com/CDH-DevTeam/arosenius-api/commit/89d3b44c08d39ce600a6629f88aed912b8585439
